MDScreen:
    name: "wiki"

    MDFloatLayout:
        md_bg_color: 1, 1, 1, 1

        Label:
            text: "Plant Wiki"
            font_name: "fonts/SFProDisplay-Heavy.ttf"
            font_size: "49sp"
            pos_hint: {"center_x": .340,"center_y": .88}
            color: rgba(114,122,67,255)

        ScrollView:
            size_hint: (1, 0.790)
            pos_hint: {"center_x": 0.5, "y": 0.02}

            MDGridLayout:
                cols: 1
                adaptive_height: True
                padding: dp(10)
                spacing: dp(10)

                MDBoxLayout:
                    orientation: "horizontal"
                    size_hint_y: None
                    height: dp(180)
                    spacing: dp(10)

                    FitImage:
                        source: "assets/dieffenbachia.jpg"
                        size_hint_y: None
                        height: dp(150)

                    MDLabel:
                        text: "Dieffenbachia improves indoor air quality by filtering toxins."
                        font_name: "fonts/SFProText-Regular.ttf"
                        font_size: "14sp"
                        halign: "left"
                        theme_text_color: "Secondary"

                MDBoxLayout:
                    orientation: "horizontal"
                    size_hint_y: None
                    height: dp(180)
                    spacing: dp(10)

                    FitImage:
                        source: "assets/philodendron.jpg"
                        size_hint_y: None
                        height: dp(150)

                    MDLabel:
                        text: "Philodendron are easy to care for and helps purify air."
                        font_name: "fonts/SFProText-Regular.ttf"
                        font_size: "14sp"
                        halign: "left"
                        theme_text_color: "Secondary"

                MDBoxLayout:
                    orientation: "horizontal"
                    size_hint_y: None
                    height: dp(180)
                    spacing: dp(10)

                    FitImage:
                        source: "assets/elephant.jpg"
                        size_hint_y: None
                        height: dp(150)

                    MDLabel:
                        text: "Elephant Ear are large leaves that provides humidity and tropical feel."
                        font_name: "fonts/SFProText-Regular.ttf"
                        font_size: "14sp"
                        halign: "left"
                        theme_text_color: "Secondary"

                MDBoxLayout:
                    orientation: "horizontal"
                    size_hint_y: None
                    height: dp(180)
                    spacing: dp(10)

                    FitImage:
                        source: "assets/snakeplant.jpg"
                        size_hint_y: None
                        height: dp(150)

                    MDLabel:
                        text: "Snake Plant releases oxygen at night, improving sleep quality."
                        font_name: "fonts/SFProText-Regular.ttf"
                        font_size: "14sp"
                        halign: "left"
                        theme_text_color: "Secondary"

                MDBoxLayout:
                    orientation: "horizontal"
                    size_hint_y: None
                    height: dp(180)
                    spacing: dp(10)

                    FitImage:
                        source: "assets/goldenpothos.png"
                        size_hint_y: None
                        height: dp(150)

                    MDLabel:
                        text: "Golden Pothos are low maintenance and removes indoor pollutants."
                        font_name: "fonts/SFProText-Regular.ttf"
                        font_size: "14sp"
                        halign: "left"
                        theme_text_color: "Secondary"

                MDBoxLayout:
                    orientation: "horizontal"
                    size_hint_y: None
                    height: dp(180)
                    spacing: dp(10)

                    FitImage:
                        source: "assets/rededgedracaena.jpg"
                        size_hint_y: None
                        height: dp(150)

                    MDLabel:
                        text: "Red-Edged Dracaena absorbs harmful toxins from the air."
                        font_name: "fonts/SFProText-Regular.ttf"
                        font_size: "14sp"
                        halign: "left"
                        theme_text_color: "Secondary"

                MDBoxLayout:
                    orientation: "horizontal"
                    size_hint_y: None
                    height: dp(180)
                    spacing: dp(10)

                    FitImage:
                        source: "assets/zzplant.jpg"
                        size_hint_y: None
                        height: dp(150)

                    MDLabel:
                        text: "ZZ Plant thrives in low light and improves air quality."
                        font_name: "fonts/SFProText-Regular.ttf"
                        font_size: "14sp"
                        halign: "left"
                        theme_text_color: "Secondary"

                MDBoxLayout:
                    orientation: "horizontal"
                    size_hint_y: None
                    height: dp(180)
                    spacing: dp(10)

                    FitImage:
                        source: "assets/Aloe-b.jpg"
                        size_hint_y: None
                        height: dp(150)

                    MDLabel:
                        text: "Aloe Vera provides natural healing for burns and skin care."
                        font_name: "fonts/SFProText-Regular.ttf"
                        font_size: "14sp"
                        halign: "left"
                        theme_text_color: "Secondary"

                MDBoxLayout:
                    orientation: "horizontal"
                    size_hint_y: None
                    height: dp(180)
                    spacing: dp(10)

                    FitImage:
                        source: "assets/rubber.jpg"
                        size_hint_y: None
                        height: dp(150)

                    MDLabel:
                        text: "Rubber Plant absorbs toxins and increases humidity indoors."
                        font_name: "fonts/SFProText-Regular.ttf"
                        font_size: "14sp"
                        halign: "left"
                        theme_text_color: "Secondary"

                MDBoxLayout:
                    orientation: "horizontal"
                    size_hint_y: None
                    height: dp(180)
                    spacing: dp(10)

                    FitImage:
                        source: "assets/spiderplant.jpg"
                        size_hint_y: None
                        height: dp(150)

                    MDLabel:
                        text: "Spider Plant are excellent at removing indoor air pollutants."
                        font_name: "fonts/SFProText-Regular.ttf"
                        font_size: "14sp"
                        halign: "left"
                        theme_text_color: "Secondary"

        MDBoxLayout:
            size_hint_y: None
            height: dp(120)  # Matches the icon size
            md_bg_color: rgba(245, 245, 245, 255)  # Light gray background
            pos_hint: {"x": 0, "y": -0.009}  # Sticks to the bottom
            padding: dp(5)
            spacing: dp(5)

            MDBoxLayout:
                orientation: "vertical"
                spacing: dp(5)
                size_hint_x: None
                width: dp(100)
                pos_hint: {"center_x": 0.2}

                MDIconButton:
                    icon: "home"
                    theme_text_color: "Custom"
                    user_font_size: "100sp"
                    text_color: rgba(114,122,67,255)
                    pos_hint: {"center_x": 0.5}
                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "dashboard"

                Label:
                    text: "Home"
                    font_name: "fonts/SFProText-Regular.ttf"
                    font_size: "18sp"
                    halign: "center"
                    color: rgba(114,122,67,255)

            MDBoxLayout:
                orientation: "vertical"
                spacing: dp(5)
                size_hint_x: None
                width: dp(100)
                pos_hint: {"center_x": 0.4}

                MDIconButton:
                    icon: "sprout"
                    theme_text_color: "Custom"
                    user_font_size: "100sp"
                    text_color: rgba(114,122,67,255)
                    pos_hint: {"center_x": 0.5}
                    on_release:
                        root.manager.transition.direction = "up"
                        root.manager.current = "plantsmenu"

                Label:
                    text: "Plants"
                    font_name: "fonts/SFProText-Regular.ttf"
                    font_size: "18sp"
                    halign: "center"
                    color: rgba(114,122,67,255)

            MDBoxLayout:
                orientation: "vertical"
                spacing: dp(5)
                size_hint_x: None
                width: dp(100)
                pos_hint: {"center_x": 0.6}

                MDIconButton:
                    icon: "web"
                    theme_text_color: "Custom"
                    user_font_size: "100sp"
                    text_color: rgba(114,122,67,255)
                    pos_hint: {"center_x": 0.5}
                    on_release:
                        root.manager.transition.direction = "up"
                        root.manager.current = "wiki"

                Label:
                    text: "Wiki"
                    font_name: "fonts/SFProText-Regular.ttf"
                    font_size: "18sp"
                    halign: "center"
                    color: rgba(114,122,67,255)

            MDBoxLayout:
                orientation: "vertical"
                spacing: dp(5)
                size_hint_x: None
                width: dp(100)
                pos_hint: {"center_x": 0.8}

                MDIconButton:
                    icon: "camera"
                    theme_text_color: "Custom"
                    user_font_size: "150sp"
                    text_color: rgba(114,122,67,255)
                    pos_hint: {"center_x": 0.5}
                    on_release:
                        root.manager.transition.direction = "right"
                        root.manager.current = "sensor"

                Label:
                    text: "Sensor"
                    font_name: "fonts/SFProText-Regular.ttf"
                    font_size: "18sp"
                    halign: "center"
                    color: rgba(114,122,67,255)
